#include <stdio.h>

int main() {
    int num, i;

                unsigned long long factorial = 1; 

                                printf("Enter an integer: ");
                                                    scanf("%d", &num);

                                                                            // Factorial does not exist for negative numbers
                                                                                                        if (num < 0) {
                                                                                                                                            printf("Error! Factorial of a negative number doesn't exist.\n");
                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                    // Loop to multiply numbers from 1 to num
                                                                                                                                                                                                                                                                                            for (i = 1; i <= num; ++i) {
                                                                                                                                                                                                                                                                                                                                                                factorial *= i; // Same as factorial = factorial * i;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Factorial of %d = %llu\n", num, factorial);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }